### ISSUE TITLE
PDU encoder

### ISSUE THREAD

**Issue by bronte2k7** [qotto/smspdudecoder#7]
really lacking

**Comment by alexpirine** [comment]
Hi @bronte2k7 , could you please describe your use case and give an example of the API you wish you had?

**Comment by bronte2k7** [comment]
Hello
Your code is very neat. So my example will be in your style.

```python
class PDU:
	def encode(data={}) :
		return {'encoded_data': '', 'length': 'int'} # perhaps some more necessary data

	def decode(data=None):
		return {'decoded_data': '', 'length': 'int'} # perhaps some more necessary data

# p.s. I really hope that you understand me
```

Of all the libraries I've seen, only yours works with python 3, but lacks an encoder)))

**Comment by alexpirine** [comment]
Closing this for now, since the project is only capable of decoding right now.

If anyone is interested in a Python encoder, it would be helpful to present use cases to move forward. And even better, creating a PR :)
